Feature/styling
mugberto/bookstore pull request #4
Opened 2021-08-26 22:14 UTC by mugberto

# Project: Bookstore CMS
In the branch, we added style to our app to match the UI design given [here](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378)

To log in to Zeplin, use the following credentials:
- username: microverse_student
- password: c9A6EEh8hTam

2021-08-26 22:46 UTC, Davidosky007 requested changes
## Hi @mugberto 👋, 

Good job so far! 💪 
* The repo looks professional.✔️
* Git/GitHub flow best practices have been followed✔️
* There are no linter errors✔️
* You have descriptive PR✔️
## * There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-26 22:46 UTC, Davidosky007 commented on src/components/appComponents/booksComponents/AddBookForm.css
> +  width: 17.813rem;
* Kindly adjust the width to fit the screen currently the width overflows causing a scroll bar to appear below 
![image](https://user-images.githubusercontent.com/52497246/131045382-c8af025f-f5f7-49e9-a554-c6b2f141c4c5.png)

2021-08-27 20:38 UTC, mugberto commented
Hi @Davidosky007, I added a little bit of responsiveness to solve the issue. Before, I had used the exact measures from the design as requested.

2021-08-27 21:11 UTC, Emmyn5600 approved these changes
Hi, 

Good job so far! 👏🏼 @mugberto

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewer.
 
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-28 13:30 UTC, merged